package com.kidsroutine.core.model

/**
 * A 3-day mini story arc generated by Gemini.
 * Each chapter is one day's task. All three chapters share the same narrative.
 *
 * Stored in: Firestore  story_arcs/{arcId}
 * Injected:  Into daily tasks on days 1, 2, 3 of the arc.
 */
data class StoryChapter(
    val day: Int = 1,            // 1, 2, or 3
    val chapterTitle: String = "",
    val narrative: String = "",  // 1-sentence story context shown to child
    val taskTitle: String = "",
    val taskDescription: String = "",
    val estimatedDurationSec: Int = 60,
    val category: String = "CREATIVITY",
    val difficulty: String = "MEDIUM",
    val xpReward: Int = 50,
    val type: String = "STORY"
)

data class StoryArc(
    val arcId: String = "",
    val arcTitle: String = "",   // e.g. "The Lost Star"
    val arcEmoji: String = "📖",
    val theme: String = "",      // e.g. "Space Adventure"
    val childAge: Int = 0,
    val familyId: String = "",
    val chapters: List<StoryChapter> = emptyList(),  // always 3
    val startDate: String = "",  // "2026-03-24"  (day 1 date)
    val currentDay: Int = 1,     // 1, 2, or 3
    val isComplete: Boolean = false,
    val createdAt: Long = 0L
)

/** What the Cloud Function returns */
data class StoryArcResponse(
    val success: Boolean = false,
    val arc: StoryArc? = null,
    val cached: Boolean = false,
    val quotaRemaining: Int = 0
)